<?xml version="1.0"?>
<!--
mecanum_robot.urdf.xacro - FIXED VERSION
FIX: Corrected nested link structure for lidar2
-->

<robot name="mecanum_robot" xmlns:xacro="http://ros.org/wiki/xacro">
  
  <!-- ================================================================== -->
  <!-- PROPERTIES -->
  <!-- ================================================================== -->
  
  <xacro:property name="base_length" value="0.48"/>
  <xacro:property name="base_width" value="0.47"/>
  <xacro:property name="base_height" value="0.15"/>
  <xacro:property name="base_mass" value="20.0"/>
  
  <xacro:property name="wheel_radius" value="0.075"/>
  <xacro:property name="wheel_width" value="0.06"/>
  <xacro:property name="wheel_mass" value="1.5"/>
  <xacro:property name="wheel_separation_x" value="0.48"/>
  <xacro:property name="wheel_separation_y" value="0.47"/>
  
  <xacro:property name="lidar_height" value="0.08"/>
  <xacro:property name="imu_height" value="0.05"/>


  <!-- ================================================================== -->
  <!-- MATERIALS -->
  <!-- ================================================================== -->
  
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1.0"/>
  </material>
  
  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>
  
  <material name="white">
    <color rgba="0.9 0.9 0.9 1.0"/>
  </material>
  
  <material name="red">
    <color rgba="0.8 0.2 0.2 1.0"/>
  </material>
  
  <material name="green">
    <color rgba="0.2 0.8 0.2 1.0"/>
  </material>
  
  <material name="orange">
    <color rgba="1.0 0.5 0.0 1.0"/>
  </material>


  <!-- ================================================================== -->
  <!-- BASE_LINK -->
  <!-- ================================================================== -->
  
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.8 0.52 ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2 + 0.05}" rpy="0 0 0"/>
      <material name="orange"/>
    </visual>
    
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2 + 0.05}" rpy="0 0 0"/>
    </collision>
    
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0 0 ${base_height/2 + 0.05 }" rpy="0 0 0"/>
      <inertia 
        ixx="${(1/12) * base_mass * (base_width*base_width + base_height*base_height)}"
        iyy="${(1/12) * base_mass * (base_length*base_length + base_height*base_height)}"
        izz="${(1/12) * base_mass * (base_length*base_length + base_width*base_width)}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>


  <!-- ================================================================== -->
  <!-- LIDAR 1 - Thân LiDAR -->
  <!-- ================================================================== -->
  
  <link name="lidar1_link">
    <visual>
      <geometry>
        <cylinder radius="0.04" length="0.04"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="black"/>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="0.04" length="0.04"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" iyy="0.0001" izz="0.0001" 
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  
  <joint name="lidar1_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar1_link"/>
    <origin xyz="0.42 0.29 0.075" rpy="0 0 3.1456"/>
  </joint>


  <!-- ================================================================== -->
  <!-- LIDAR 1 - Đế cam -->
  <!-- ================================================================== -->

  <link name="de_lidar1_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.002"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="lidar1_base_orange">
        <color rgba="1.0 0.5 0.0 1.0"/>
      </material>
    </visual>
    
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.002"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00001" iyy="0.00001" izz="0.00001"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="de_lidar1_joint" type="fixed">
    <parent link="lidar1_link"/>
    <child link="de_lidar1_link"/>
    <origin xyz="0 0 -0.021" rpy="0 0 0"/>
  </joint>


  <!-- ================================================================== -->
  <!-- LIDAR 2 - Thân LiDAR (✅ FIXED: Đóng đúng tag) -->
  <!-- ================================================================== -->
  
  <link name="lidar2_link">
    <visual>
      <geometry>
        <cylinder radius="0.04" length="0.04"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="black"/>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="0.04" length="0.04"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" iyy="0.0001" izz="0.0001"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  
  <joint name="lidar2_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar2_link"/>
    <origin xyz="-0.42 -0.29 0.075" rpy="0 0 0"/>
  </joint>


  <!-- ================================================================== -->
  <!-- LIDAR 2 - Đế cam (✅ FIXED: Tách riêng ra ngoài) -->
  <!-- ================================================================== -->
  
  <link name="de_lidar2_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.002"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="lidar2_base_orange">
        <color rgba="1.0 0.5 0.0 1.0"/>
      </material>
    </visual>
    
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.002"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00001" iyy="0.00001" izz="0.00001"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="de_lidar2_joint" type="fixed">
    <parent link="lidar2_link"/>
    <child link="de_lidar2_link"/>
    <origin xyz="0 0 -0.021" rpy="0 0 0"/>
  </joint>


  <!-- ================================================================== -->
  <!-- IMU SENSOR -->
  <!-- ================================================================== -->
  
  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.05 0.04 0.02"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    
    <collision>
      <geometry>
        <box size="0.05 0.04 0.02"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00001" iyy="0.00001" izz="0.00001"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${imu_height}" rpy="0 0 -1.57"/>
  </joint>


  <!-- ================================================================== -->
  <!-- WHEELS -->
  <!-- ================================================================== -->

  <!-- FRONT LEFT -->
  <link name="wheel_fl_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="black"/>
    </visual>
    
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
    </collision>
    
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <inertia 
        ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
        iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
        izz="${(1/2) * wheel_mass * wheel_radius*wheel_radius}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="wheel_fl_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_fl_link"/>
    <origin xyz="${wheel_separation_x/2} ${wheel_separation_y/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>


  <!-- FRONT RIGHT -->
  <link name="wheel_fr_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="4.71239 0 0"/>
      <material name="black"/>
    </visual>
    
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="4.71239 0 0"/>
    </collision>
    
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy="4.71239 0 0"/>
      <inertia 
        ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
        iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
        izz="${(1/2) * wheel_mass * wheel_radius*wheel_radius}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="wheel_fr_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_fr_link"/>
    <origin xyz="${wheel_separation_x/2} ${-wheel_separation_y/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>


  <!-- REAR LEFT -->
  <link name="wheel_rl_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="black"/>
    </visual>
    
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
    </collision>
    
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <inertia 
        ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
        iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
        izz="${(1/2) * wheel_mass * wheel_radius*wheel_radius}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="wheel_rl_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_rl_link"/>
    <origin xyz="${-wheel_separation_x/2} ${wheel_separation_y/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>


  <!-- REAR RIGHT -->
  <link name="wheel_rr_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="4.71239 0 0"/>
      <material name="black"/>
    </visual>
    
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="4.71239 0 0"/>
    </collision>
    
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy="4.71239 0 0"/>
      <inertia 
        ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
        iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
        izz="${(1/2) * wheel_mass * wheel_radius*wheel_radius}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="wheel_rr_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_rr_link"/>
    <origin xyz="${-wheel_separation_x/2} ${-wheel_separation_y/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>


  <!-- ================================================================== -->
  <!-- FRONT MARKER -->
  <!-- ================================================================== -->
  
  <link name="front_marker">
    <visual>
      <geometry>
        <box size="0.05 0.52 0.02"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="red"/>
    </visual>
  </link>
  
  <joint name="front_marker_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_marker"/>
    <origin xyz="0.375 0 ${base_height + 0.06}" rpy="0 0 0"/>
  </joint>

</robot>